RegisterNetEvent('system:notify', function(source, player, subject, message, content, icon, flash)
    AddTextEntry('SystemNotification', message)
    BeginTextCommandThefeedPost('SystemNotification')
    EndTextCommandThefeedPostMessagetext(content, content, false, icon, player, subject)
    EndTextCommandThefeedPostTicker(flash or false, true)
end)

RegisterNetEvent('system:helpText', function(playerId, message)
    SetNotificationTextEntry("STRING")
    AddTextComponentString(message)
    DrawNotification(true, false)
end)

RegisterNetEvent('system:playerUpdated', function(type, data)
    System.SetPlayerData(type, data)
end)
